# Generated by Django 4.2 on 2023-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspect',
            new_name='Inspection',
        ),
        migrations.AlterField(
            model_name='business_type',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business_type',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business_type',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business_type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
